services:
  orchestra-api:
    volumes:
      - ../services/orchestra-api/target/classes:/app/target/classes
    ports:
      - "8085:8085"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_HOST=${APP_RABBITMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  orchestra-executor:
    volumes:
      - ../services/orchestra-executor/target/classes:/app/target/classes
    ports:
      - "5006:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_RABBITMQ_HOST=${APP_RABBITMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  orchestra-web:
    volumes:
      - ../apps/orchestra-web:/app
      - /app/node_modules
    command: npm run start
    ports:
      - "3000:3000"

  ai-service:
    volumes:
      - ../services/ai-service/target/classes:/app/target/classes
    ports:
      - "8090:8080"
      - "5007:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://${APP_DB_HOST}:${APP_DB_PORT}/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
