version: '3.9'

services:
  orchestra-api:
    volumes:
      - ../services/orchestra-api/target/classes:/app/target/classes
    ports:
      - "8085:8085"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=${APP_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${APP_DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${APP_DB_PASSWORD}
      - SPRING_RABBITMQ_HOST=${APP_RABBITMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${APP_RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${APP_RABBITMQ_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  orchestra-executor:
    volumes:
      - ../services/orchestra-executor/target/classes:/app/target/classes
    ports:
      - "5006:5005"
    environment:
      - SPRING_RABBITMQ_HOST=${APP_RABBITMQ_HOST}
      - SPRING_RABBITMQ_USERNAME=${APP_RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${APP_RABBITMQ_PASSWORD}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005

  orchestra-web:
    volumes:
      - ../apps/orchestra-web:/app
      - /app/node_modules
    command: npm run start
    ports:
      - "3000:3000"
